theme: jekyll-theme-dinky
title: Girls Who Code Summer Field Trip
description: This site contains a tutorial for developing an Alexa Skill.
repository_url: https://github.com/gwc-summer-newark-nj/gwc-summer-newark-nj.github.io/
